
-- Auto generated alive statements
-- import SSA.Projects.InstCombine.AliveAutoGenerated

-- Pure math statements needed to proof alive statements
import SSA.Projects.InstCombine.AliveStatements

-- The semantics for the MLIR base dialect
import SSA.Projects.InstCombine.Base

-- An tactic for automatically proofing the alive math statements
import SSA.Projects.InstCombine.TacticAuto
