
-- Auto generated alive statements
-- Do not import these into the default tree, because they take a long
-- time to elaborate and typecheck.
-- Import this by default, since the file has a `#exit` that checks the first two
--   theorems. This ensures that the file (and transitively, its dependencies) are not broken.
import SSA.Projects.InstCombine.AliveAutoGenerated

-- Pure math statements needed to prove alive statements.
-- Include these, as they are reasonably fast to typecheck.
import SSA.Projects.InstCombine.AliveStatements

-- The semantics for the MLIR base dialect
import SSA.Projects.InstCombine.Base

-- An tactic for automatically proofing the alive math statements
import SSA.Projects.InstCombine.TacticAuto
