/-
  TODO: fix auto-generation script with new syntax
-/

/- `AliveAutoGenerated.lean` is where the broken translation lives. -/
import SSA.Projects.InstCombine.AliveAutoGenerated -- file auto generated from alive with syntax
import SSA.Projects.InstCombine.AliveStatements -- pure math statements of alive theorems
import SSA.Projects.InstCombine.Base -- base dialect
import SSA.Projects.InstCombine.Tactic -- `simp_alive` tactic to eliminate MLIR overhead.
import SSA.Projects.InstCombine.TacticAuto -- decision procedure.