
import SSA.Projects.InstCombine.tests.LLVM.g2004h02h23hShiftShiftOverflow
import SSA.Projects.InstCombine.tests.LLVM.g2004h11h22hMissedhandhfold
import SSA.Projects.InstCombine.tests.LLVM.g2008h02h16hSDivOverflow2
import SSA.Projects.InstCombine.tests.LLVM.g2008h02h23hMulSub
import SSA.Projects.InstCombine.tests.LLVM.g2008h05h31hAddBool
import SSA.Projects.InstCombine.tests.LLVM.g2008h05h31hBools
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h08hSubAnd
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h09hSubAndError
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h11hRemAnd
import SSA.Projects.InstCombine.tests.LLVM.g2010h11h01hlshrhmask
import SSA.Projects.InstCombine.tests.LLVM.g2010h11h23hDistributed
import SSA.Projects.InstCombine.tests.LLVM.gadd2
import SSA.Projects.InstCombine.tests.LLVM.gadd4
import SSA.Projects.InstCombine.tests.LLVM.gaddhmaskhneg
import SSA.Projects.InstCombine.tests.LLVM.gaddhmask
import SSA.Projects.InstCombine.tests.LLVM.gaddhshift
import SSA.Projects.InstCombine.tests.LLVM.gaddhshlhsdivhtohsrem
import SSA.Projects.InstCombine.tests.LLVM.gaddnegneg
import SSA.Projects.InstCombine.tests.LLVM.gadd_or_sub
import SSA.Projects.InstCombine.tests.LLVM.gaddsubhconstanthfolding
import SSA.Projects.InstCombine.tests.LLVM.gand2
import SSA.Projects.InstCombine.tests.LLVM.gandhorhand
import SSA.Projects.InstCombine.tests.LLVM.gandhorhnot
import SSA.Projects.InstCombine.tests.LLVM.gandhxorhmerge
import SSA.Projects.InstCombine.tests.LLVM.gandhxorhor
import SSA.Projects.InstCombine.tests.LLVM.gand
import SSA.Projects.InstCombine.tests.LLVM.gannotations
import SSA.Projects.InstCombine.tests.LLVM.gapinthadd
import SSA.Projects.InstCombine.tests.LLVM.gapinthandhorhand
import SSA.Projects.InstCombine.tests.LLVM.gapinthandhxorhmerge
import SSA.Projects.InstCombine.tests.LLVM.gapinthand
import SSA.Projects.InstCombine.tests.LLVM.gapinthmul1
import SSA.Projects.InstCombine.tests.LLVM.gapinthmul2
import SSA.Projects.InstCombine.tests.LLVM.gapinthnot
import SSA.Projects.InstCombine.tests.LLVM.gapinthor
import SSA.Projects.InstCombine.tests.LLVM.gapinthrem1
import SSA.Projects.InstCombine.tests.LLVM.gapinthrem2
import SSA.Projects.InstCombine.tests.LLVM.gapinthshifthsimplify
import SSA.Projects.InstCombine.tests.LLVM.gapinthshift
import SSA.Projects.InstCombine.tests.LLVM.gapinthsub
import SSA.Projects.InstCombine.tests.LLVM.gapinthxor1
import SSA.Projects.InstCombine.tests.LLVM.gapinthxor2
import SSA.Projects.InstCombine.tests.LLVM.gashrhdemand
import SSA.Projects.InstCombine.tests.LLVM.gashrhlshr
import SSA.Projects.InstCombine.tests.LLVM.gavghlsb
import SSA.Projects.InstCombine.tests.LLVM.gbinophandhshifts
import SSA.Projects.InstCombine.tests.LLVM.gbinophofhdisplacedhshifts
import SSA.Projects.InstCombine.tests.LLVM.gcanonicalizehashrhshlhtohmasking
import SSA.Projects.InstCombine.tests.LLVM.gcanonicalizehlshrhshlhtohmasking
import SSA.Projects.InstCombine.tests.LLVM.gcanonicalizehshlhlshrhtohmasking
import SSA.Projects.InstCombine.tests.LLVM.gdemand_shrink_nsw
import SSA.Projects.InstCombine.tests.LLVM.gdemorgan
import SSA.Projects.InstCombine.tests.LLVM.gdistribute
import SSA.Projects.InstCombine.tests.LLVM.gdivhi1
import SSA.Projects.InstCombine.tests.LLVM.gdivhshift
import SSA.Projects.InstCombine.tests.LLVM.gearly_constfold_changes_IR
import SSA.Projects.InstCombine.tests.LLVM.gexact
import SSA.Projects.InstCombine.tests.LLVM.gfoldhinchofhaddhofhnothxhandhyhtohsubhxhfromhy
import SSA.Projects.InstCombine.tests.LLVM.gfoldhsubhofhnothtohinchofhadd
import SSA.Projects.InstCombine.tests.LLVM.gfreehinversion
import SSA.Projects.InstCombine.tests.LLVM.ggethlowbitmaskhuptohandhincludinghbit
import SSA.Projects.InstCombine.tests.LLVM.ghighhbithsignmask
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnegationhouthofhbiashcalculationhwithhconstant
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnegationhouthofhbiashcalculation
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnothfromhashrhoperand
import SSA.Projects.InstCombine.tests.LLVM.ghoisthxorhbyhconstanthfromhxorhbyhvalue
import SSA.Projects.InstCombine.tests.LLVM.gicmphmulhand
import SSA.Projects.InstCombine.tests.LLVM.gicmphmul
import SSA.Projects.InstCombine.tests.LLVM.ginverthvariablehmaskhinhmaskedhmergehscalar
import SSA.Projects.InstCombine.tests.LLVM.glowhbithsplat
import SSA.Projects.InstCombine.tests.LLVM.glshr
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehadd
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehandhofhors
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehor
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehxor
import SSA.Projects.InstCombine.tests.LLVM.gmisch2002
import SSA.Projects.InstCombine.tests.LLVM.gmul_fold
import SSA.Projects.InstCombine.tests.LLVM.gmulhpow2
import SSA.Projects.InstCombine.tests.LLVM.gnegatedhbitmask
import SSA.Projects.InstCombine.tests.LLVM.gnothadd
import SSA.Projects.InstCombine.tests.LLVM.gnot
import SSA.Projects.InstCombine.tests.LLVM.gorhshiftedhmasks
import SSA.Projects.InstCombine.tests.LLVM.gorhxorhxor
import SSA.Projects.InstCombine.tests.LLVM.gorhxor
import SSA.Projects.InstCombine.tests.LLVM.gpr14365
import SSA.Projects.InstCombine.tests.LLVM.gpr53357
import SSA.Projects.InstCombine.tests.LLVM.gpreservedhanalyses
import SSA.Projects.InstCombine.tests.LLVM.gpullhbinophthroughhshift
import SSA.Projects.InstCombine.tests.LLVM.greassociatehnuw
import SSA.Projects.InstCombine.tests.LLVM.grem
import SSA.Projects.InstCombine.tests.LLVM.gsdivh1
import SSA.Projects.InstCombine.tests.LLVM.gsdivhcanonicalize
import SSA.Projects.InstCombine.tests.LLVM.gsdivhexacthbyhnegativehpowerhofhtwo
import SSA.Projects.InstCombine.tests.LLVM.gsdivhexacthbyhpowerhofhtwo
import SSA.Projects.InstCombine.tests.LLVM.gsethlowbitshmaskhcanonicalize
import SSA.Projects.InstCombine.tests.LLVM.gshifthaddhinseltpoison
import SSA.Projects.InstCombine.tests.LLVM.gshifthadd
import SSA.Projects.InstCombine.tests.LLVM.gshifthamounthreassociation
import SSA.Projects.InstCombine.tests.LLVM.gshifthlogic
import SSA.Projects.InstCombine.tests.LLVM.gshifthshift
import SSA.Projects.InstCombine.tests.LLVM.gshifthsra
import SSA.Projects.InstCombine.tests.LLVM.gshlhbo
import SSA.Projects.InstCombine.tests.LLVM.gshlhdemand
import SSA.Projects.InstCombine.tests.LLVM.gshlhfactor
import SSA.Projects.InstCombine.tests.LLVM.gshlhsub
import SSA.Projects.InstCombine.tests.LLVM.gsignext
import SSA.Projects.InstCombine.tests.LLVM.gsremhcanonicalize
import SSA.Projects.InstCombine.tests.LLVM.gsubhandhorhneghxor
import SSA.Projects.InstCombine.tests.LLVM.gsubhfromhsub
import SSA.Projects.InstCombine.tests.LLVM.gsubhnot
import SSA.Projects.InstCombine.tests.LLVM.gsubhofhnegatiblehinseltpoison
import SSA.Projects.InstCombine.tests.LLVM.gsubhofhnegatible
import SSA.Projects.InstCombine.tests.LLVM.gsubhorhandhxor
import SSA.Projects.InstCombine.tests.LLVM.gsubhxorhorhneghand
import SSA.Projects.InstCombine.tests.LLVM.gsubhxor
import SSA.Projects.InstCombine.tests.LLVM.gunfoldhmaskedhmergehwithhconsthmaskhscalar
import SSA.Projects.InstCombine.tests.LLVM.gxor2
import SSA.Projects.InstCombine.tests.LLVM.gxorhofhor
import SSA.Projects.InstCombine.tests.LLVM.gxor
