import SSA.Projects.InstCombine.lean.g2004h02h23hShiftShiftOverflow
import SSA.Projects.InstCombine.lean.g2004h11h22hMissedhandhfold
import SSA.Projects.InstCombine.lean.g2008h02h16hSDivOverflow2
import SSA.Projects.InstCombine.lean.g2008h02h23hMulSub
import SSA.Projects.InstCombine.lean.g2008h05h31hAddBool
import SSA.Projects.InstCombine.lean.g2008h05h31hBools
import SSA.Projects.InstCombine.lean.g2008h07h08hSubAnd
import SSA.Projects.InstCombine.lean.g2008h07h09hSubAndError
import SSA.Projects.InstCombine.lean.g2008h07h11hRemAnd
import SSA.Projects.InstCombine.lean.g2010h11h01hlshrhmask
import SSA.Projects.InstCombine.lean.g2010h11h23hDistributed
import SSA.Projects.InstCombine.lean.gadd2
import SSA.Projects.InstCombine.lean.gadd4
import SSA.Projects.InstCombine.lean.gaddhmaskhneg
import SSA.Projects.InstCombine.lean.gaddhmask
import SSA.Projects.InstCombine.lean.gaddhshift
import SSA.Projects.InstCombine.lean.gaddhshlhsdivhtohsrem
import SSA.Projects.InstCombine.lean.gaddnegneg
import SSA.Projects.InstCombine.lean.gadd_or_sub
import SSA.Projects.InstCombine.lean.gaddsubhconstanthfolding
import SSA.Projects.InstCombine.lean.gand2
import SSA.Projects.InstCombine.lean.gandhorhand
import SSA.Projects.InstCombine.lean.gandhorhnot
import SSA.Projects.InstCombine.lean.gandhxorhmerge
import SSA.Projects.InstCombine.lean.gandhxorhor
import SSA.Projects.InstCombine.lean.gand
import SSA.Projects.InstCombine.lean.gannotations
import SSA.Projects.InstCombine.lean.gapinthadd
import SSA.Projects.InstCombine.lean.gapinthandhorhand
import SSA.Projects.InstCombine.lean.gapinthandhxorhmerge
import SSA.Projects.InstCombine.lean.gapinthand
import SSA.Projects.InstCombine.lean.gapinthmul1
import SSA.Projects.InstCombine.lean.gapinthmul2
import SSA.Projects.InstCombine.lean.gapinthnot
import SSA.Projects.InstCombine.lean.gapinthor
import SSA.Projects.InstCombine.lean.gapinthrem1
import SSA.Projects.InstCombine.lean.gapinthrem2
import SSA.Projects.InstCombine.lean.gapinthshifthsimplify
import SSA.Projects.InstCombine.lean.gapinthshift
import SSA.Projects.InstCombine.lean.gapinthsub
import SSA.Projects.InstCombine.lean.gapinthxor1
import SSA.Projects.InstCombine.lean.gapinthxor2
import SSA.Projects.InstCombine.lean.gashrhdemand
import SSA.Projects.InstCombine.lean.gashrhlshr
import SSA.Projects.InstCombine.lean.gbinophandhshifts
import SSA.Projects.InstCombine.lean.gbinophofhdisplacedhshifts
import SSA.Projects.InstCombine.lean.gcanonicalizehashrhshlhtohmasking
import SSA.Projects.InstCombine.lean.gcanonicalizehlshrhshlhtohmasking
import SSA.Projects.InstCombine.lean.gcanonicalizehshlhlshrhtohmasking
import SSA.Projects.InstCombine.lean.gdemand_shrink_nsw
import SSA.Projects.InstCombine.lean.gdemorgan
import SSA.Projects.InstCombine.lean.gdistribute
import SSA.Projects.InstCombine.lean.gdivhi1
import SSA.Projects.InstCombine.lean.gdivhshift
import SSA.Projects.InstCombine.lean.gearly_constfold_changes_IR
import SSA.Projects.InstCombine.lean.gexact
import SSA.Projects.InstCombine.lean.gfoldhinchofhaddhofhnothxhandhyhtohsubhxhfromhy
import SSA.Projects.InstCombine.lean.gfoldhsubhofhnothtohinchofhadd
import SSA.Projects.InstCombine.lean.gfreehinversion
import SSA.Projects.InstCombine.lean.ggethlowbitmaskhuptohandhincludinghbit
import SSA.Projects.InstCombine.lean.ghighhbithsignmask
import SSA.Projects.InstCombine.lean.ghoisthnegationhouthofhbiashcalculationhwithhconstant
import SSA.Projects.InstCombine.lean.ghoisthnegationhouthofhbiashcalculation
import SSA.Projects.InstCombine.lean.ghoisthnothfromhashrhoperand
import SSA.Projects.InstCombine.lean.ghoisthxorhbyhconstanthfromhxorhbyhvalue
import SSA.Projects.InstCombine.lean.gicmphmulhand
import SSA.Projects.InstCombine.lean.gicmphmul
import SSA.Projects.InstCombine.lean.ginverthvariablehmaskhinhmaskedhmergehscalar
import SSA.Projects.InstCombine.lean.glowhbithsplat
import SSA.Projects.InstCombine.lean.glshr
import SSA.Projects.InstCombine.lean.gmaskedhmergehadd
import SSA.Projects.InstCombine.lean.gmaskedhmergehandhofhors
import SSA.Projects.InstCombine.lean.gmaskedhmergehor
import SSA.Projects.InstCombine.lean.gmaskedhmergehxor
import SSA.Projects.InstCombine.lean.gmisch2002
import SSA.Projects.InstCombine.lean.gmul_fold
import SSA.Projects.InstCombine.lean.gmulhpow2
import SSA.Projects.InstCombine.lean.gnegatedhbitmask
import SSA.Projects.InstCombine.lean.gnothadd
import SSA.Projects.InstCombine.lean.gnot
import SSA.Projects.InstCombine.lean.gorhshiftedhmasks
import SSA.Projects.InstCombine.lean.gorhxorhxor
import SSA.Projects.InstCombine.lean.gorhxor
import SSA.Projects.InstCombine.lean.gpr14365
import SSA.Projects.InstCombine.lean.gpr53357
import SSA.Projects.InstCombine.lean.gpullhbinophthroughhshift
import SSA.Projects.InstCombine.lean.greassociatehnuw
import SSA.Projects.InstCombine.lean.grem
import SSA.Projects.InstCombine.lean.gsdivh1
import SSA.Projects.InstCombine.lean.gsdivhcanonicalize
import SSA.Projects.InstCombine.lean.gsdivhexacthbyhnegativehpowerhofhtwo
import SSA.Projects.InstCombine.lean.gsdivhexacthbyhpowerhofhtwo
import SSA.Projects.InstCombine.lean.gsethlowbitshmaskhcanonicalize
import SSA.Projects.InstCombine.lean.gshifthaddhinseltpoison
import SSA.Projects.InstCombine.lean.gshifthadd
import SSA.Projects.InstCombine.lean.gshifthamounthreassociation
import SSA.Projects.InstCombine.lean.gshifthlogic
import SSA.Projects.InstCombine.lean.gshifthshift
import SSA.Projects.InstCombine.lean.gshifthsra
import SSA.Projects.InstCombine.lean.gshlhbo
import SSA.Projects.InstCombine.lean.gshlhdemand
import SSA.Projects.InstCombine.lean.gshlhfactor
import SSA.Projects.InstCombine.lean.gshlhsub
import SSA.Projects.InstCombine.lean.gsignext
import SSA.Projects.InstCombine.lean.gsremhcanonicalize
import SSA.Projects.InstCombine.lean.gsubhandhorhneghxor
import SSA.Projects.InstCombine.lean.gsubhfromhsub
import SSA.Projects.InstCombine.lean.gsubhnot
import SSA.Projects.InstCombine.lean.gsubhofhnegatiblehinseltpoison
import SSA.Projects.InstCombine.lean.gsubhofhnegatible
import SSA.Projects.InstCombine.lean.gsubhorhandhxor
import SSA.Projects.InstCombine.lean.gsubhxorhorhneghand
import SSA.Projects.InstCombine.lean.gsubhxor
import SSA.Projects.InstCombine.lean.gunfoldhmaskedhmergehwithhconsthmaskhscalar
import SSA.Projects.InstCombine.lean.gxor2
import SSA.Projects.InstCombine.lean.gxorhofhor
import SSA.Projects.InstCombine.lean.gxor
