hdel_ntests: 100   # default number of goals to take.
hdel_bv_widths: [4, 8, 16, 32, 64] # number of hackers delight widths. 
hdel_nreps: 2 # number of repetitions to run hacker's delight tests.
# Time parsed using 'humanfriendly'.  https://humanfriendly.readthedocs.io/en/latest/api.html?highlight=parse_timespan#humanfriendly.parse_timespan
hdel_timeout: "30min" # parsed using 'humanfriendly
hdel_nthreads: 8 # number of threads to use for hacker's delight tests.
seed: 42 # random number generator seed.


