; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128-n32:64"
declare void @use(i16)

define i16 @mul_no_common_bits_disjoint(i16 %x, i16 %y) {
; CHECK-LABEL: @mul_no_common_bits_disjoint(
; CHECK-NEXT:    [[TMP1:%.*]] = add i16 [[Y:%.*]], 1
; CHECK-NEXT:    [[R:%.*]] = mul i16 [[X:%.*]], [[TMP1]]
; CHECK-NEXT:    ret i16 [[R]]
;
  %m = mul nuw nsw i16 %x, %y
  %r = or disjoint i16 %m, %x
  ret i16 %r
}

define i1 @auto_gen_81_logical_fmf(double %a, double %b) {
; CHECK-LABEL: @auto_gen_81_logical_fmf(
; CHECK-NEXT:    [[RETVAL:%.*]] = fcmp fast oeq double [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret i1 [[RETVAL]]
;
  %cmp = fcmp fast ule double %a, %b
  %cmp1 = fcmp fast oge double %a, %b
  %retval = select i1 %cmp, i1 %cmp1, i1 false
  ret i1 %retval
}
