hdel_bv_widths: [4, 8, 16, 32, 64] # number of hackers delight widths.
hdel_nreps: 2 # number of repetitions to run hacker's delight tests.
hdel_timeout_sec: 1800 # timeout for hacker's delight test cases.
hdel_memout_mb: 8000 # memout for hacker's delight test cases.
hdel_nthreads: 8 # number of threads to use for hacker's delight tests.
seed: 42 # random number generator seed.


