import SSA.Projects.InstCombine.tests.LLVM.gicmphmul_proof
import SSA.Projects.InstCombine.tests.LLVM.gsdivhexacthbyhpowerhofhtwo_proof
import SSA.Projects.InstCombine.tests.LLVM.grem_proof
import SSA.Projects.InstCombine.tests.LLVM.gcanonicalizehlshrhshlhtohmasking_proof
import SSA.Projects.InstCombine.tests.LLVM.gshifthadd_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddnegneg_proof
import SSA.Projects.InstCombine.tests.LLVM.gdistribute_proof
import SSA.Projects.InstCombine.tests.LLVM.gmul_fold_proof
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnegationhouthofhbiashcalculationhwithhconstant_proof
import SSA.Projects.InstCombine.tests.LLVM.g2004h02h23hShiftShiftOverflow_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h09hSubAndError_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddsubhconstanthfolding_proof
import SSA.Projects.InstCombine.tests.LLVM.ghoisthxorhbyhconstanthfromhxorhbyhvalue_proof
import SSA.Projects.InstCombine.tests.LLVM.gsignext_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h11hRemAnd_proof
import SSA.Projects.InstCombine.tests.LLVM.gsdivhexacthbyhnegativehpowerhofhtwo_proof
import SSA.Projects.InstCombine.tests.LLVM.gbinophofhdisplacedhshifts_proof
import SSA.Projects.InstCombine.tests.LLVM.gshifthsra_proof
import SSA.Projects.InstCombine.tests.LLVM.gandhorhnot_proof
import SSA.Projects.InstCombine.tests.LLVM.gexact_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhnot_proof
import SSA.Projects.InstCombine.tests.LLVM.gsremhcanonicalize_proof
import SSA.Projects.InstCombine.tests.LLVM.g2004h11h22hMissedhandhfold_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthnot_proof
import SSA.Projects.InstCombine.tests.LLVM.gicmphmulhand_proof
import SSA.Projects.InstCombine.tests.LLVM.gunfoldhmaskedhmergehwithhconsthmaskhscalar_proof
import SSA.Projects.InstCombine.tests.LLVM.gshifthaddhinseltpoison_proof
import SSA.Projects.InstCombine.tests.LLVM.gand_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h07h08hSubAnd_proof
import SSA.Projects.InstCombine.tests.LLVM.gpullhbinophthroughhshift_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthshifthsimplify_proof
import SSA.Projects.InstCombine.tests.LLVM.gnothadd_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h02h16hSDivOverflow2_proof
import SSA.Projects.InstCombine.tests.LLVM.gshlhsub_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthor_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gfreehinversion_proof
import SSA.Projects.InstCombine.tests.LLVM.gsdivh1_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhfromhsub_proof
import SSA.Projects.InstCombine.tests.LLVM.gshlhdemand_proof
import SSA.Projects.InstCombine.tests.LLVM.gshlhfactor_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthand_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhofhnegatiblehinseltpoison_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddhshlhsdivhtohsrem_proof
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnegationhouthofhbiashcalculation_proof
import SSA.Projects.InstCombine.tests.LLVM.gxorhofhor_proof
import SSA.Projects.InstCombine.tests.LLVM.gnot_proof
import SSA.Projects.InstCombine.tests.LLVM.gandhxorhor_proof
import SSA.Projects.InstCombine.tests.LLVM.gmulhpow2_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddhmaskhneg_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhorhandhxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gshifthshift_proof
import SSA.Projects.InstCombine.tests.LLVM.gandhxorhmerge_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthadd_proof
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehadd_proof
import SSA.Projects.InstCombine.tests.LLVM.gsethlowbitshmaskhcanonicalize_proof
import SSA.Projects.InstCombine.tests.LLVM.gdivhshift_proof
import SSA.Projects.InstCombine.tests.LLVM.ginverthvariablehmaskhinhmaskedhmergehscalar_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthxor1_proof
import SSA.Projects.InstCombine.tests.LLVM.gorhxorhxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gannotations_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddhshift_proof
import SSA.Projects.InstCombine.tests.LLVM.greassociatehnuw_proof
import SSA.Projects.InstCombine.tests.LLVM.gxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gpr53357_proof
import SSA.Projects.InstCombine.tests.LLVM.gnegatedhbitmask_proof
import SSA.Projects.InstCombine.tests.LLVM.gearly_constfold_changes_IR_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhandhorhneghxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthmul1_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhofhnegatible_proof
import SSA.Projects.InstCombine.tests.LLVM.gcanonicalizehashrhshlhtohmasking_proof
import SSA.Projects.InstCombine.tests.LLVM.gaddhmask_proof
import SSA.Projects.InstCombine.tests.LLVM.gxor2_proof
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthandhxorhmerge_proof
import SSA.Projects.InstCombine.tests.LLVM.gshlhbo_proof
import SSA.Projects.InstCombine.tests.LLVM.gadd2_proof
import SSA.Projects.InstCombine.tests.LLVM.ggethlowbitmaskhuptohandhincludinghbit_proof
import SSA.Projects.InstCombine.tests.LLVM.glowhbithsplat_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h05h31hBools_proof
import SSA.Projects.InstCombine.tests.LLVM.gadd_or_sub_proof
import SSA.Projects.InstCombine.tests.LLVM.gashrhdemand_proof
import SSA.Projects.InstCombine.tests.LLVM.gshifthamounthreassociation_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthrem2_proof
import SSA.Projects.InstCombine.tests.LLVM.gbinophandhshifts_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthmul2_proof
import SSA.Projects.InstCombine.tests.LLVM.gsubhxorhorhneghand_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthxor2_proof
import SSA.Projects.InstCombine.tests.LLVM.glshr_proof
import SSA.Projects.InstCombine.tests.LLVM.gdivhi1_proof
import SSA.Projects.InstCombine.tests.LLVM.gandhorhand_proof
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehandhofhors_proof
import SSA.Projects.InstCombine.tests.LLVM.gfoldhsubhofhnothtohinchofhadd_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h02h23hMulSub_proof
import SSA.Projects.InstCombine.tests.LLVM.gfoldhinchofhaddhofhnothxhandhyhtohsubhxhfromhy_proof
import SSA.Projects.InstCombine.tests.LLVM.gdemorgan_proof
import SSA.Projects.InstCombine.tests.LLVM.g2008h05h31hAddBool_proof
import SSA.Projects.InstCombine.tests.LLVM.gsdivhcanonicalize_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthshift_proof
import SSA.Projects.InstCombine.tests.LLVM.ghighhbithsignmask_proof
import SSA.Projects.InstCombine.tests.LLVM.gand2_proof
import SSA.Projects.InstCombine.tests.LLVM.ghoisthnothfromhashrhoperand_proof
import SSA.Projects.InstCombine.tests.LLVM.g2010h11h23hDistributed_proof
import SSA.Projects.InstCombine.tests.LLVM.gdemand_shrink_nsw_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthandhorhand_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthrem1_proof
import SSA.Projects.InstCombine.tests.LLVM.gashrhlshr_proof
import SSA.Projects.InstCombine.tests.LLVM.gapinthsub_proof
import SSA.Projects.InstCombine.tests.LLVM.gadd4_proof
import SSA.Projects.InstCombine.tests.LLVM.gpr14365_proof
import SSA.Projects.InstCombine.tests.LLVM.gorhxor_proof
import SSA.Projects.InstCombine.tests.LLVM.gmisch2002_proof
import SSA.Projects.InstCombine.tests.LLVM.gmaskedhmergehor_proof
