/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7fcea134-cfac-4390-8a80-0d75c6fc938e
-/

/-
We define a stream type `MyStream` (as `Stream` is already defined in Mathlib) and a bisimulation relation `Bisim` on it. We prove that `Bisim` is an equivalence relation, specifically proving transitivity in `stream_bisim_trans`. Note that the theorem is named `stream_bisim_trans` because `trans` is a reserved name in Lean/Mathlib. The proof uses coinduction and several helper lemmas handling `none` values and stepping through the streams.
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Stream

#check Stream'
#check Stream'.get
#check Stream'.drop

def MyStream (β : Type) := Stream' (Option β)

def BisimGen {α : Type} (R : MyStream α → MyStream α → Prop) (a b : MyStream α) : Prop :=
  ∃ n m, R (a.drop (n + 1)) (b.drop (m + 1)) ∧
    Stream'.get a n = Stream'.get b m ∧
    (∀ i < n, Stream'.get a i = none) ∧
    (∀ j < m, Stream'.get b j = none)

lemma BisimGen_mono {α : Type} : Monotone (@BisimGen α) := by
  -- To prove monotonicity, we need to show that if $R \subseteq S$, then $\text{BisimGen } R \subseteq \text{BisimGen } S$.
  intros R S hRS x y hxy
  simp [BisimGen];
  -- Since $R \subseteq S$, the condition for $BisimGen R x y$ implies the same condition for $BisimGen S x y$.
  obtain ⟨n, m, hR, hxy⟩ := hxy;
  use n, m;
  aesop

def Bisim {α : Type} : MyStream α → MyStream α → Prop :=
  OrderHom.gfp ⟨@BisimGen α, BisimGen_mono⟩

infix:50 " ~ " => Bisim

theorem Bisim.coinduct {α : Type} {R : MyStream α → MyStream α → Prop}
    (h : ∀ a b, R a b → BisimGen R a b) :
    ∀ a b, R a b → a ~ b := by
      aesop;
      refine' ⟨ _, _ ⟩;
      exact True;
      aesop

theorem Bisim.step {α : Type} {a b : MyStream α} {n m : Nat} :
    Bisim (a.drop (n + 1)) (b.drop (m + 1)) →
    Stream'.get a n = Stream'.get b m →
    (∀ i < n, Stream'.get a i = none) →
    (∀ j < m, Stream'.get b j = none) →
    Bisim a b := by
      intros h1 h2 h3 h4;
      -- By definition of bisimilarity, we need to show that $a \sim b$.
      unfold Bisim at *; simp_all +decide [ Stream'.get ] ;
      -- Let's unfold the definition of the bisimulation relation.
      unfold OrderHom.gfp at *; simp_all +decide [ BisimGen ] ;
      -- Let's choose the relation R that includes the pairs (a, b) and (Stream'.drop (n + 1) a, Stream'.drop (m + 1) b).
      obtain ⟨R, hR⟩ := h1;
      use fun x y => x = a ∧ y = b ∨ R x y;
      aesop;
      intro x y hxy; aesop;
      · constructor <;> aesop;
      · have := left _ _ h_1; unfold BisimGen at this; aesop;
        constructor <;> aesop

#check Stream'.cons

/-
Bisimulation is symmetric.
-/
lemma Bisim_symm {α : Type} {a b : MyStream α} : a ~ b → b ~ a := by
  intro hab;
  -- By definition of bisimulation, we need to show that for all `n`, `a.get n = b.get n` and `a.drop n ≤ b.drop n` and `b.drop n ≤ a.drop n`.
  apply Bisim.coinduct;
  swap;
  tauto;
  intro a b hab;
  obtain ⟨ n, m, hnm ⟩ := hab;
  obtain ⟨ f, hf ⟩ := m;
  aesop;
  obtain ⟨ n, m, hnm ⟩ := left _ _ hnm;
  refine' ⟨ m, n, _, _, _, _ ⟩ <;> aesop;
  exact?

/-
If two streams are bisimilar via witnesses n and m, then dropping any prefix of the first stream (up to n) preserves bisimilarity to the second stream.
-/
lemma Bisim_drop_of_witness {α : Type} {a b : MyStream α} {n m : Nat} :
    Bisim (a.drop (n + 1)) (b.drop (m + 1)) →
    Stream'.get a n = Stream'.get b m →
    (∀ i < n, Stream'.get a i = none) →
    (∀ j < m, Stream'.get b j = none) →
    ∀ k < n, Bisim (a.drop (k + 1)) b := by
  intro h_bisim h_eq h_none_a h_none_b k hk
  -- We want to show a.drop (k+1) ~ b
  -- We can use Bisim.step with N = n - (k+1) and M = m
  apply Bisim.step (n := n - (k + 1)) (m := m)
  · -- Bisim (a.drop (k+1).drop (N+1)) (b.drop (m+1))
    -- a.drop (k+1).drop (n - (k+1) + 1) = a.drop (n+1)
    convert h_bisim using 1;
    rw [ Stream'.drop_drop, tsub_add_eq_add_tsub ( by linarith ) ];
    rw [ add_tsub_cancel_of_le ( by linarith ) ]
  · -- get
    norm_num +zetaDelta at *;
    grind
  · -- none a
    exact fun i hi => by simpa [ Nat.add_comm ] using h_none_a ( k + 1 + i ) ( by linarith [ Nat.sub_add_cancel ( by linarith : k + 1 ≤ n ) ] ) ;
  · -- none b
    assumption

/-
Unfolding lemma for Bisim.
-/
lemma Bisim_eq {α : Type} {a b : MyStream α} : Bisim a b ↔ BisimGen Bisim a b := by
  have h_bisim_rec : Bisim = fun a b => BisimGen (Bisim : MyStream α → MyStream α → Prop) a b := by
    apply le_antisymm;
    · apply OrderHom.gfp_le;
      intro R hR;
      -- Since R is a bisimulation, we have R ≤ Bisim.
      have hR_le_Bisim : R ≤ Bisim := by
        apply Bisim.coinduct; assumption;
      intro a b hab;
      exact hR a b hab |> fun ⟨ n, m, hnm, h_eq, h_left, h_right ⟩ => ⟨ n, m, hR_le_Bisim _ _ hnm, h_eq, h_left, h_right ⟩;
    · intro a b h;
      convert Bisim.step _ _ _ _;
      exact h.choose
      exact h.choose_spec.choose
      exact h.choose_spec.choose_spec.1
      exact h.choose_spec.choose_spec.2.1
      exact h.choose_spec.choose_spec.2.2.1
      exact h.choose_spec.choose_spec.2.2.2;
  exact?

/-
If a stream matches another stream after dropping a prefix of nones, then it matches from the beginning.
-/
lemma Bisim_cons_none {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim (a.drop (k + 1)) b →
    (∀ i ≤ k, Stream'.get a i = none) →
    Bisim a b := by
      -- Let's unfold the BisimGen relation.
      intros h_drop h_none
      rw [Bisim_eq];
      -- Assume `a.drop (k+1) ~ b`. Then `BisimGen Bisim (a.drop (k+1)) b`.
      obtain ⟨n', m', h_gen, h_eq, h_none_left, h_none_right⟩ : ∃ n' m', Bisim (a.drop (k + 1 + n' + 1)) (b.drop (m' + 1)) ∧ (a.drop (k + 1)).get n' = b.get m' ∧ (∀ i < n', (a.drop (k + 1)).get i = none) ∧ (∀ j < m', b.get j = none) := by
        rw [Bisim_eq] at h_drop;
        cases h_drop ; aesop;
      use k + 1 + n', m';
      aesop;
      by_cases hi : i ≤ k;
      · exact h_none i hi;
      · convert h_none_left ( i - ( k + 1 ) ) ( by omega ) using 1;
        rw [ Nat.add_sub_cancel' ( by linarith ) ]

/-
If a stream matches another stream after dropping a prefix of nones, then it matches from the beginning.
-/
lemma Bisim_cons_none_v2 {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim (a.drop (k + 1)) b →
    (∀ i ≤ k, Stream'.get a i = none) →
    Bisim a b := by
      exact?

/-
If a stream matches another stream after dropping a prefix of nones, then it matches from the beginning.
-/
lemma Bisim_cons_none_v3 {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim (a.drop (k + 1)) b →
    (∀ i ≤ k, Stream'.get a i = none) →
    Bisim a b := by
      exact?

/-
Bisimulation is reflexive.
-/
lemma Bisim_refl {α : Type} (a : MyStream α) : a ~ a := by
  apply Bisim.coinduct (R := fun x y => x = y)
  · intro x y h
    rw [h]
    use 0, 0
    simp
  · rfl

/-
If a stream matches another stream after dropping a prefix of nones, then it matches from the beginning.
-/
lemma Bisim_cons_none_final {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim (a.drop (k + 1)) b →
    (∀ i ≤ k, Stream'.get a i = none) →
    Bisim a b := by
      exact?

/-
Dropping a prefix of the second stream preserves bisimilarity if the prefix consists of nones.
-/
lemma Bisim_drop_right {α : Type} {a b : MyStream α} {n m : Nat} :
    Bisim (a.drop (n + 1)) (b.drop (m + 1)) →
    Stream'.get a n = Stream'.get b m →
    (∀ i < n, Stream'.get a i = none) →
    (∀ j < m, Stream'.get b j = none) →
    ∀ k < m, Bisim a (b.drop (k + 1)) := by
  intros h_bisim h_eq h_none_a h_none_b k hk
  apply Bisim_symm
  apply Bisim_drop_of_witness (n := m) (m := n)
  · apply Bisim_symm
    exact h_bisim
  · rw [h_eq]
  · exact h_none_b
  · exact h_none_a
  · exact hk

/-
If a stream matches another stream after dropping a prefix of nones, then it matches from the beginning.
-/
lemma Bisim_cons_none_proven {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim (a.drop (k + 1)) b →
    (∀ i ≤ k, Stream'.get a i = none) →
    Bisim a b := by
      bound;
      -- Apply the lemma Bisim_cons_none_final with the given hypotheses.
      apply Bisim_cons_none_final a_1 a_2

/-
Bisimulation implies the transitivity relation.
-/
lemma Bisim_le_R {α : Type} {a c : MyStream α} : a ~ c → ∃ b, a ~ b ∧ b ~ c := by
  intro h
  use c
  constructor
  · exact h
  · apply Bisim_refl

/-
Bisimulation skips nones.
-/
lemma Bisim_skip_nones {α : Type} {a b : MyStream α} {k : Nat} :
    Bisim a b →
    (∀ i < k, Stream'.get b i = none) →
    ∃ n m, Bisim (a.drop (n + 1)) (b.drop (m + 1)) ∧
           Stream'.get a n = Stream'.get b m ∧
           (∀ i < n, Stream'.get a i = none) ∧
           (∀ j < m, Stream'.get b j = none) ∧
           m ≥ k := by
             intro h₁ h₂; induction' k with k ih;
             · rw [ Bisim_eq ] at h₁; aesop;
             · obtain ⟨ n, m, h₃, h₄, h₅, h₆, h₇ ⟩ := ih fun i hi => h₂ i ( Nat.lt_succ_of_lt hi );
               by_cases h₈ : m = k;
               · -- Since $m = k$, we can apply the induction hypothesis to $m + 1$.
                 obtain ⟨ n', m', h₈, h₉, h₁₀, h₁₁ ⟩ := Bisim_eq.mp h₃;
                 use n + 1 + n', m + 1 + m'; (
                 simp_all +arith +decide [ Stream'.get ];
                 aesop;
                 · simp_all +arith +decide [ Stream'.drop ];
                   exact h₉;
                 · by_cases hi : i < n + 1;
                   · cases lt_or_eq_of_le ( Nat.le_of_lt_succ hi ) <;> aesop;
                   · cases le_iff_exists_add'.mp ( by linarith : n + 1 ≤ i ) ; aesop;
                     convert h₁₀ ( w ) ( by linarith ) using 1;
                 · by_cases hj : j ≤ m;
                   · exact h₂ j hj;
                   · specialize h₁₁ ( j - ( m + 1 ) ) ; simp_all +arith +decide [ Nat.sub_add_cancel ( by linarith : m + 1 ≤ j ) ];
                     by_cases hj' : j - ( m + 1 ) < m' <;> simp_all +decide [ Stream'.drop ];
                     · rwa [ Nat.sub_add_cancel ( by linarith ) ] at h₁₁;
                     · grind);
               · exact ⟨ n, m, h₃, h₄, h₅, h₆, Nat.lt_of_le_of_ne h₇ ( Ne.symm h₈ ) ⟩

/-
If a stream starts with none, dropping the first element preserves bisimilarity.
-/
lemma Bisim_drop_none_left {α : Type} {a b : MyStream α} :
    Bisim a b → Stream'.get a 0 = none → Bisim (a.drop 1) b := by
      intro h;
      -- Unfold `a ~ b` to `n, m`.
      obtain ⟨n, m, h_next⟩ := Bisim_eq.mp h;
      rcases n with ( _ | n ) <;> aesop;
      · rw [ eq_comm ] at left_1 ; aesop;
        -- By `Bisim_cons_none_proven`, since `b.drop (m+1)` is bisimilar to `a.drop 1` and `b` has nones up to `m+1`, we can conclude that `b` is bisimilar to `a.drop 1`.
        have h_bisim : Bisim b (Stream'.drop 1 a) := by
          apply Bisim_cons_none_proven;
          exact?;
          exact fun i hi => if hi' : i < m then right i hi' else by rw [ le_antisymm hi ( Nat.le_of_not_lt hi' ) ] ; assumption;
        exact?;
      · exact Bisim_drop_of_witness left left_1 left_2 right 0 ( Nat.zero_lt_succ _ )

/-
Bisimulation exact match for values.
-/
lemma Bisim_match_some {α : Type} {a b : MyStream α} {k : Nat} {v : α} :
    Bisim a b →
    (∀ i < k, Stream'.get b i = none) →
    Stream'.get b k = some v →
    ∃ l, Stream'.get a l = some v ∧
         (∀ i < l, Stream'.get a i = none) ∧
         Bisim (a.drop (l + 1)) (b.drop (k + 1)) := by
  intro h_bisim h_none h_some
  obtain ⟨n, m, h_next, h_eq, h_none_a, h_none_b, hm⟩ := Bisim_skip_nones h_bisim h_none
  have h_mk : m = k := by
    by_contra h_ne
    have h_gt : m > k := lt_of_le_of_ne hm (Ne.symm h_ne)
    have h_none_k : Stream'.get b k = none := h_none_b k h_gt
    rw [h_some] at h_none_k
    contradiction
  subst h_mk
  use n
  refine ⟨?_, h_none_a, h_next⟩
  rw [h_eq, h_some]

/-
Bisimulation preserves all nones.
-/
lemma Bisim_all_nones {α : Type} {a b : MyStream α} :
    Bisim a b → (∀ i, Stream'.get a i = none) → (∀ j, Stream'.get b j = none) := by
      intro h;
      -- Assume b has a value v at position j. Let k be the index of the first value in b.
      by_contra h_contra
      obtain ⟨j, v, hv⟩ : ∃ j v, b.get j = some v ∧ ∀ i < j, b.get i = none := by
        aesop;
        exact ⟨ Nat.find ( ⟨ w, by aesop ⟩ : ∃ i, Stream'.get b i ≠ none ), ⟨ Classical.choose ( Option.ne_none_iff_exists'.mp ( Nat.find_spec ( ⟨ w, by aesop ⟩ : ∃ i, Stream'.get b i ≠ none ) ) ), Classical.choose_spec ( Option.ne_none_iff_exists'.mp ( Nat.find_spec ( ⟨ w, by aesop ⟩ : ∃ i, Stream'.get b i ≠ none ) ) ) ⟩, fun i hi => by aesop ⟩;
      have := Bisim_match_some h hv.2 hv.1;
      aesop

/-
Streams of all nones are bisimilar.
-/
lemma Bisim_all_nones_bisim {α : Type} {a b : MyStream α} :
    (∀ i, Stream'.get a i = none) → (∀ j, Stream'.get b j = none) → a ~ b := by
  intros ha hb
  apply Bisim.coinduct (R := fun x y => (∀ i, Stream'.get x i = none) ∧ (∀ j, Stream'.get y j = none))
  · intro x y h
    rcases h with ⟨hx, hy⟩
    use 0, 0
    refine ⟨?_, ?_, ?_, ?_⟩
    · constructor
      · intro i
        rw [Stream'.get_drop]
        apply hx
      · intro j
        rw [Stream'.get_drop]
        apply hy
    · rw [hx 0, hy 0]
    · intro i hi; omega
    · intro j hj; omega
  · exact ⟨ha, hb⟩

/-
Bisimulation satisfies the generator property for transitivity.
-/
lemma BisimGen_trans {α : Type} {x z : MyStream α} :
    (∃ y, x ~ y ∧ y ~ z) → BisimGen (fun a b => ∃ c, a ~ c ∧ c ~ b) x z := by
      cases isEmpty_or_nonempty α <;> aesop;
      · -- Since α is empty, any element in α must be none. Therefore, BisimGen holds because both components are none.
        use 0, 0;
        aesop;
        · have h_all_nones : ∀ s : MyStream α, (∀ i, (s.get i) = none) := by
            exact fun s i => Option.eq_none_iff_forall_not_mem.mpr fun x hx => h.elim x;
          exact ⟨ z, by exact Bisim_all_nones_bisim ( fun i => h_all_nones _ _ ) ( fun i => h_all_nones _ _ ), by exact Bisim_all_nones_bisim ( fun i => h_all_nones _ _ ) ( fun i => h_all_nones _ _ ) ⟩;
        · exact Subsingleton.elim _ _;
      · -- Split into cases based on whether z has a value or not.
        by_cases hz : ∃ k v, z.get k = some v ∧ ∀ i < k, z.get i = none;
        · obtain ⟨ k, v, hv₁, hv₂ ⟩ := hz;
          -- By definition of bisimulation, there exists some $l, m$ such that $x \sim y$, $y \sim z$, and $x$ and $y$ match at $l, m$.
          obtain ⟨ l, hl₁, hl₂, hl₃ ⟩ := Bisim_match_some right hv₂ hv₁;
          -- By definition of bisimulation, there exists some $n, m$ such that $x \sim y$, $y \sim z$, and $x$ and $y$ match at $n, m$.
          obtain ⟨ n, hn₁, hn₂, hn₃ ⟩ := Bisim_match_some left hl₂ hl₁;
          refine' ⟨ n, k, _, _, _, _ ⟩ <;> aesop;
        · -- Since z has no values, it must be all nones.
          have hz_all_nones : ∀ k, z.get k = none := by
            contrapose! hz;
            -- By the well-ordering principle, there exists a least element in the set of indices where `z` has a value.
            obtain ⟨k, hk⟩ : ∃ k, z.get k ≠ none ∧ ∀ j < k, z.get j = none := by
              exact ⟨ Nat.find hz, Nat.find_spec hz, fun j hj => by aesop ⟩;
            cases h : z.get k <;> aesop;
          -- Since w is bisimilar to z and z is all nones, w must also be all nones.
          have hw_all_nones : ∀ k, w.get k = none := by
            have := Bisim_all_nones ( Bisim_symm ‹_› ) ; aesop;
          -- Since x is bisimilar to w and w is all nones, x must also be all nones.
          have hx_all_nones : ∀ k, x.get k = none := by
            apply Bisim_all_nones;
            exacts [ Bisim_symm left, hw_all_nones ];
          use 0, 0;
          aesop;
          use w.drop 1;
          aesop;
          · exact?;
          · exact?

/-
Bisimulation preserves all nones.
-/
lemma Bisim_all_nones_v2 {α : Type} {a b : MyStream α} :
    Bisim a b → (∀ i, Stream'.get a i = none) → (∀ j, Stream'.get b j = none) := by
      exact?

/-
Bisimulation preserves all nones.
-/
lemma Bisim_all_nones_proven {α : Type} {a b : MyStream α} :
    Bisim a b → (∀ i, Stream'.get a i = none) → (∀ j, Stream'.get b j = none) := by
      exact?

/-
Bisimulation satisfies the generator property for transitivity.
-/
lemma BisimGen_trans_proven {α : Type} {x z : MyStream α} :
    (∃ y, x ~ y ∧ y ~ z) → BisimGen (fun a b => ∃ c, a ~ c ∧ c ~ b) x z := by
      exact?

/-
Bisimulation generator property for all nones case.
-/
lemma BisimGen_trans_none {α : Type} {x y z : MyStream α} :
    Bisim x y → Bisim y z → (∀ k, Stream'.get z k = none) →
    BisimGen (fun a b => ∃ c, a ~ c ∧ c ~ b) x z := by
  intro hxy hyz h_none_z
  have h_none_y : ∀ i, Stream'.get y i = none := Bisim_all_nones_proven (Bisim_symm hyz) h_none_z
  have h_none_x : ∀ i, Stream'.get x i = none := Bisim_all_nones_proven (Bisim_symm hxy) h_none_y
  use 0, 0
  refine ⟨?_, ?_, ?_, ?_⟩
  · use y.drop 1
    constructor
    · apply Bisim_all_nones_bisim
      · intro i; rw [Stream'.get_drop]; apply h_none_x
      · intro i; rw [Stream'.get_drop]; apply h_none_y
    · apply Bisim_all_nones_bisim
      · intro i; rw [Stream'.get_drop]; apply h_none_y
      · intro i; rw [Stream'.get_drop]; apply h_none_z
  · rw [h_none_x 0, h_none_z 0]
  · intro i hi; omega
  · intro j hj; omega

/-
Bisimulation generator property for value case.
-/
lemma BisimGen_trans_some {α : Type} {x y z : MyStream α} :
    Bisim x y → Bisim y z → (∃ k, Stream'.get z k ≠ none) →
    BisimGen (fun a b => ∃ c, a ~ c ∧ c ~ b) x z := by
      simp +zetaDelta at *;
      intro hxy hyz k hk_nonnone
      by_contra h_contra;
      exact h_contra ( BisimGen_trans <| by aesop )

/-
Bisimulation satisfies the generator property for transitivity (final).
-/
lemma BisimGen_trans_final {α : Type} {x z : MyStream α} :
    (∃ y, x ~ y ∧ y ~ z) → BisimGen (fun a b => ∃ c, a ~ c ∧ c ~ b) x z := by
  intro h
  obtain ⟨y, hxy, hyz⟩ := h
  by_cases h_val : ∃ k, Stream'.get z k ≠ none
  · exact BisimGen_trans_some hxy hyz h_val
  · push_neg at h_val
    exact BisimGen_trans_none hxy hyz h_val

/-
Transitivity of bisimulation.
-/
theorem stream_bisim_trans {α : Type} {a b c : MyStream α} : a ~ b → b ~ c → a ~ c := by
  intros hab hbc
  apply Bisim.coinduct (R := fun x z => ∃ y, x ~ y ∧ y ~ z)
  · intro x z h
    exact BisimGen_trans_final h
  · exact ⟨b, hab, hbc⟩

/-
Transitivity of bisimulation.
-/
theorem bisim_transitivity {α : Type} {a b c : MyStream α} : a ~ b → b ~ c → a ~ c := by
  intros hab hbc
  apply Bisim.coinduct (R := fun x z => ∃ y, x ~ y ∧ y ~ z)
  · intro x z h
    exact BisimGen_trans_final h
  · exact ⟨b, hab, hbc⟩
