from pathlib import Path
"""
# This script generates Lean proofs for constant lowering of RISC-V li instructions.
It generates a riscv lefthandside and an llvm constant right hand side for each integer in the 
range [-max_val, max_val].
Additionally, it generates a proof that the two are equivalent as follows :

def llvm_const_lower_riscv_li0 : LLVMPeepholeRewriteRefine 64 [] :=
  {lhs:= const_llvm_o, rhs:= li_riscv_o,
   correct := by
    unfold const_llvm_0 li_riscv_
    simp_peephole
    simp_riscv
    simp_alive_ops
    simp
  }
"""
def generate_lean_proofs(max_val=25):
    header = """-- AUTOGENERATED Lean file: Constant lowering for RISC-V li instructions\n
import SSA.Projects.LLVMRiscV.PeepholeRefine
import SSA.Projects.LLVMRiscV.simpproc
import SSA.Projects.RISCV64.Tactic.SimpRiscV

 open LLVMRiscV\n 
    """
    body = ""
    rewrite_names = []
    for i in range(-max_val, max_val + 1):
        name_suffix = f"n{-i}" if i < 0 else str(i)
        li_def = f"""def li_riscv_{name_suffix} := [LV| {{
    ^entry ():
      %0 = "li"() {{imm = {i} : !i64}}  : (!i64) -> (!i64)
      %1 = "builtin.unrealized_conversion_cast"(%0) : (!i64) -> (i64)
      llvm.return %1 : i64
  }}]\n"""

        llvm_def = f"""def const_llvm_{name_suffix} : Com  LLVMPlusRiscV [] .pure (.llvm (.bitvec 64))  := [LV| {{
    ^entry ():
      %1 = llvm.mlir.constant ({i}) : i64
      llvm.return %1 : i64
  }}]\n"""
        proof = f"""def llvm_const_lower_riscv_li{name_suffix} : LLVMPeepholeRewriteRefine 64 [] :=
  {{lhs:= const_llvm_{name_suffix}, rhs:= li_riscv_{name_suffix},
   correct := by
    unfold const_llvm_{name_suffix} li_riscv_{name_suffix}
    simp_peephole
    simp_riscv
    simp_alive_ops
    simp
  }}\n"""
        rewrite_names.append(f"llvm_const_lower_riscv_li{name_suffix}")
        body += li_def + llvm_def + proof + "\n"
    #create an array to hold all the rewrites to later pass to the rewriter 
    array_definition = "def all_const_llvm_const_lower_riscv_li : List (LLVMPeepholeRewriteRefine 64 []) :=\n  [\n"
    array_definition += ",\n  ".join(rewrite_names)
    array_definition += "\n  ]\n\n"
    return header + body + array_definition

# Add global array of rewrites

# get the parent directory because I placed the script in a dedicated folder.
script_dir = Path(__file__).parent
parent_dir = script_dir.parent
output_file = parent_dir / "const.lean"

# writting to lean file
with open(output_file, "w") as f:
    f.write(generate_lean_proofs(50)) #printing non-neg. constants up to 50
