name = "Medusa"
version = "0.1.0"
testDriver = "MedusaTest"
defaultTargets = ["Medusa"]

[[lean_lib]]
name = "Medusa"

[[lean_lib]]
name = "MedusaTest"

[[require]]
name = "fp-lean"
git = "https://github.com/opencompl/fp-lean"
rev = "5e45c0f"

