name: Evaluation (Namespace)
on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Lean-MLIR on NS
    runs-on:
      - nscloud-ubuntu-24.04-amd64-32x64-with-cache
      - nscloud-cache-tag-my-custom-cache
      - nscloud-cache-size-100gb
      - nscloud-git-mirror-5gb
    steps:
      - name: Checkout code (use nscloud)
        uses: namespacelabs/nscloud-checkout-action@v7

      - name: Cache Elan && Lake Folders
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.elan
            .lake
            Blase/.lake
            TacBench/.lake

      - name: Install Elan & Lean
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version

      - name: Make lake available
        run: |
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build Lean-MLIR & Mathlib
        # We build Mathlib from scratch as this reduces the build artifacts that are stored in the cache. Previous experiments
        # led to savings from avoiding a full Mathlib cache in the order of a couple hundred MBs.
        run: |
          lake -R build

  test-blase:
    name: Test Blase
    runs-on:
      - nscloud-ubuntu-24.04-amd64-32x64-with-cache
      - nscloud-cache-tag-my-custom-cache
      - nscloud-cache-size-100gb
      - nscloud-git-mirror-5gb
    needs: build
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code (use nscloud)
        uses: namespacelabs/nscloud-checkout-action@v7

      - name: Cache Elan && Lake Folders
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.elan
            .lake
            Blase/.lake
            TacBench/.lake

      - name: Install Elan & Lean
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version

      - name: Add Lean to PATH
        run: |
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build Lean-MLIR (should be all in cache)
        run: |
          lake -R build

      - name: Run Blase Test Suite
        run: |
          lake build BlaseTest
