name: Nix ci
on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs-unstable=channel:nixpkgs-unstable:nixpkgs=channel:nixpkgs-unstable
      - name: "⚙️ Confirm nix-shell is functional"
        run: nix-shell
      - name: "🐍 Check Python dependencies are available"
        run: nix-shell --run './bv-evaluation/check-imports.sh'


